spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USER_NAME}
    password: ${DB_PASSWORD}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: false
        use_sql_comments: true
  data:
    redis:
      host: localhost
      port: 6379

server:
  servlet:
    session:
      tracking-modes: cookie

jwt:
  secret:
    key: ${JWT_KEY}
  accessTokenValidityInMs: ${AT_MS}
  refreshTokenValidityInMs: ${RT_MS}

cloud:
  aws:
    s3:
      bucket: ${AWS_BUCKET_NAME}
    stack.auto: false
    region:
      static: ${AWS_BUCKET_REGION}
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}